library(mgcv)
mcycle <- MASS::mcycle
head(mcycle)
plot(mcycle)
lm_mod <- lm(accel ~ times, data = mcycle)
termplot(lm_mod, partial.resid = TRUE, se = TRUE)
gam_mod <- gam(accel ~ s(times), data = mcycle)
plot(gam_mod, residuals = TRUE, pch = 1)
coef(gam_mod)
gam_mod_k3 <- gam(accel ~ s(times, k = 3), data = mcycle)
gam_mod_k20 <- gam(accel ~ s(times, k = 20), data = mcycle)
par(mfrow = c(1, 2))
plot(gam_mod_k3, residuals = TRUE, pch = 1)
plot(gam_mod_k20, residuals = TRUE, pch = 1)
gam_mod_sk <- gam(accel ~ s(times, k = 50), data = mcycle, sp = 0.0001)
plot(gam_mod_sk, residuals = TRUE, pch = 1)